### ISSUE TITLE
compiling failed

### ISSUE THREAD

**Issue by jianshu93** [fuine/katome#1]
Dear Author,

When I am compiling, I got the following error:

Updating crates.io index
  Downloaded generic-array v0.12.4
   Compiling libm v0.2.1
   Compiling rand_core v0.4.2
   Compiling autocfg v0.1.7
   Compiling getrandom v0.1.16
   Compiling typenum v1.13.0
   Compiling rawpointer v0.2.1
   Compiling num-traits v0.2.14
   Compiling num-complex v0.2.4
   Compiling num-rational v0.2.4
   Compiling matrixmultiply v0.2.4
   Compiling rand_core v0.3.1
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling rand_core v0.5.1
   Compiling rand_chacha v0.2.2
   Compiling rand v0.7.3
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling num-integer v0.1.44
   Compiling num-complex v0.1.43
   Compiling num-traits v0.1.43
   Compiling num-complex v0.4.0
   Compiling approx v0.3.2
   Compiling ordered-float v0.2.3
   Compiling num-iter v0.1.42
   Compiling num-bigint v0.1.44
   Compiling num-bigint v0.4.0
   Compiling serde-value v0.3.1
   Compiling alga v0.9.3
   Compiling num-rational v0.1.42
   Compiling generic-array v0.12.4
   Compiling num v0.1.42
   Compiling chrono v0.2.25
   Compiling num-rational v0.4.0
   Compiling nalgebra v0.18.1
   Compiling log4rs v0.5.2
   Compiling num v0.4.0
   Compiling nalgebra v0.4.0
error[E0432]: unresolved import `rand::Rand`
 --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/dmat.rs:9:18
  |
9 | use rand::{self, Rand};
  |                  ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
 --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/dvec.rs:9:18
  |
9 | use rand::{self, Rand};
  |                  ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
  --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/vec.rs:10:12
   |
10 | use rand::{Rand, Rng};
   |            ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
  --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/pnt.rs:10:12
   |
10 | use rand::{Rand, Rng};
   |            ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
 --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/quat.rs:9:12
  |
9 | use rand::{Rand, Rng};
  |            ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
 --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/mat.rs:8:12
  |
8 | use rand::{Rand, Rng};
  |            ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
 --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/rot.rs:6:12
  |
6 | use rand::{Rand, Rng};
  |            ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
 --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/iso.rs:7:12
  |
7 | use rand::{Rand, Rng};
  |            ^^^^ no `Rand` in the root

error[E0432]: unresolved import `rand::Rand`
 --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.4.0/src/structs/spec/vec0.rs:6:12
  |
6 | use rand::{Rand, Rng};
  |            ^^^^ no `Rand` in the root

error: aborting due to 9 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `nalgebra`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

Any idea why?

Thanks,

Jianshu

**Comment by fuine** [comment]
This was an issue with non-exact versions of dependencies. For some reason I haven't added `Cargo.lock` when I was working on katome. I have fixed it in #2 and the project should now compile and work properly. Mind you that the project hasn't been maintained for roughly four years which is a relatively long time in the Rust world, so I'm sure it has accumulated some bit-rot.
